### ISSUE TITLE
I can't use jwt with "authorize" attribute. where am i doing wrong?

### ISSUE THREAD

**Issue by mansurdegirmenci** [NetDevPack/NetDevPack.Identity#20]
my settings

```
    
    public static void AddDbConfiguration(this IServiceCollection services, IConfiguration configuration)
    {
        services.AddDbContext<DataListContext>(opt =>
            {
                opt.UseSqlServer(configuration.GetConnectionString("DefaultConnection"),
                    builder => { builder.MigrationsAssembly(typeof(DataListContext).Assembly.FullName); });
            })
            .AddIdentity<AspNetUser, AspNetRole>(opt =>
            {
                opt.SignIn.RequireConfirmedEmail = true;
                opt.SignIn.RequireConfirmedPhoneNumber = true;
                opt.SignIn.RequireConfirmedAccount = true;
            })
            .AddUserManager<UserManager<AspNetUser>>()
            .AddRoleManager<RoleManager<AspNetRole>>()
            .AddSignInManager<SignInManager<AspNetUser>>()
            .AddErrorDescriber<TurkishIdentityErrorDescriber>()
            .AddEntityFrameworkStores<DataListContext>()
            .AddDefaultTokenProviders();

        services.AddJwtConfiguration(configuration).AddNetDevPackIdentity<AspNetUser, int>(opt => { });

        services.AddScoped<IAspNetUser, NetDevPack.Identity.User.AspNetUser>();
    }
```

mycontroller settings

```
   
   services.AddControllersWithViews(opt =>
            {
                //for Authorization
                var policy = new AuthorizationPolicyBuilder(JwtBearerDefaults.AuthenticationScheme)
                    .RequireAuthenticatedUser()
                    .Build();

                opt.Filters.Add(new AuthorizeFilter(policy));
     })
```

appsettings.json

`
"AppJwtSettings": {
    "Audience": "MyApplication.Name"
  },
`

mycontroller

```
 public async Task<IActionResult> SignIn([FromBody] LoginDto loginDto)
    { 
        var user = await _userManager.FindByEmailAsync(loginDto.Email);

        if (user is not null)
        {
            var result = await _signInManager.PasswordSignInAsync(user, loginDto.Password, loginDto.RememberMe, true);

            if (result.Succeeded)
            {
                var response = await GetJwtToken(user);
                return Ok(response);
            }

            if (result.ToString() != "Failed")
            {
                return NotFound(result.ToString());
            }
        }

        return NotFound("Email or password is incorrect");
    }

 [NonAction]
    private Task<UserResponse> GetJwtToken(AspNetUser user)
    {
        return _jwtBuilder
            .WithUserId(user.Id.ToString())
            .WithUsername(user.UserName)
            .WithEmail(user.Email)
            .WithJwtClaims()
            .WithUserClaims()
            .WithUserRoles()
            .WithRefreshToken()
            .BuildUserResponse();
    }

```
 
my error;

[23:09:22 INF] Request starting HTTP/1.1 GET https://localhost:5001/api/myinternethatlaris - -
[23:09:22 INF] Executing endpoint 'DataListWebUI.Controllers.MyInternetHatlarisController.Get (DataListWebUI)'
[23:09:22 INF] Route matched with {action = "Get", controller = "MyInternetHatlaris"}. Executing controller action with signature Microsoft.AspNetCore.Mvc.IActionResult Get(Microsoft.AspNetCore.OData.Query.ODataQueryOptions`1[DataListWebUI.ViewModels.Serverside.MyInternetHatlariDto]) on controller DataListWebUI.Controllers.MyInternetHatlarisController (DataListWebUI).
[23:09:22 INF] Failed to validate the token.
Microsoft.IdentityModel.Tokens.SecurityTokenSignatureKeyNotFoundException: IDX10501: Signature validation failed. Unable to match key:
kid: 'GySumUujvO3KXAfWoANOZg'.
Number of keys in TokenValidationParameters: '0'.
Number of keys in Configuration: '0'.
Exceptions caught:
 ''.
token: '{"alg":"PS256","kid":"GySumUujvO3KXAfWoANOZg","typ":"at+jwt"}.{"sub":"3","email":"...@gmail.com","jti":"8aa1b8ea-e5a0-4f5a-b8f0-515b7d480edc","iat":1652644903,"nbf":1652644903,"exp":1652648503,"iss":"NetDevPack.Identity","aud":"MyApplication.Name"}'.
   at Microsoft.IdentityModel.Tokens.InternalValidators.ValidateLifetimeAndIssuerAfterSignatureNotValidatedJwt(SecurityToken securityToken, Nullable`1 notBefore, Nullable`1 expires, String kid, TokenValidationParameters validationParameters, BaseConfiguration configuration, StringBuilder exceptionStrings, Int32 numKeysInConfiguration, Int32 numKeysInTokenValidationParameters)
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateSignature(String token, TokenValidationParameters validationParameters, BaseConfiguration configuration)
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateJWS(String token, TokenValidationParameters validationParameters, BaseConfiguration currentConfiguration, SecurityToken& signatureValidatedToken, ExceptionDispatchInfo& exceptionThrown)
--- End of stack trace from previous location ---
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateToken(String token, JwtSecurityToken outerToken, TokenValidationParameters validationParameters, SecurityToken& signatureValidatedToken)
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateToken(String token, TokenValidationParameters validationParameters, SecurityToken& validatedToken)
   at Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler.HandleAuthenticateAsync()
[23:09:22 INF] Bearer was not authenticated. Failure message: IDX10501: Signature validation failed. Unable to match key:
kid: 'GySumUujvO3KXAfWoANOZg'.
Number of keys in TokenValidationParameters: '0'.
Number of keys in Configuration: '0'.
Exceptions caught:
 ''.
token: '{"alg":"PS256","kid":"GySumUujvO3KXAfWoANOZg","typ":"at+jwt"}.{"sub":"3","email":"..@gmail.com","jti":"8aa1b8ea-e5a0-4f5a-b8f0-515b7d480edc","iat":1652644903,"nbf":1652644903,"exp":1652648503,"iss":"NetDevPack.Identity","aud":"MyApplication.Name"}'.
[23:09:22 INF] Authorization failed. These requirements were not met:
DenyAnonymousAuthorizationRequirement: Requires an authenticated user.
[23:09:22 INF] Authorization failed for the request at filter 'Microsoft.AspNetCore.Mvc.Authorization.AuthorizeFilter'.
[23:09:22 INF] Executing ChallengeResult with authentication schemes (["Bearer"]).
[23:09:22 INF] AuthenticationScheme: Bearer was challenged.
[23:09:22 INF] Executed action DataListWebUI.Controllers.MyInternetHatlarisController.Get (DataListWebUI) in 0.7457ms
[23:09:22 INF] Executed endpoint 'DataListWebUI.Controllers.MyInternetHatlarisController.Get (DataListWebUI)'
[23:09:22 INF] Request finished HTTP/1.1 GET https://localhost:5001/api/myinternethatlaris - - - 401 0 - 1.4608ms

**Comment by mansurdegirmenci** [comment]
I added the secret key and it was fixed.
